
// Takie symbole siê nie rozwi±zuj±... pomó¿my im ;)

// `_abort'
// `_cfmakeraw'
// `_closedir'
// `_eaccess'
// `_environ'
// `__exit'
// `_exit'
// `_fcntl'
// `_fprintf'
// `_free'
// `_fwopen'
// `_fwrite'
// `_getcwd'
// `_getegid'
// `_getenv'
// `_geteuid'
// `_gethostname'
// `_getmode'
// `_getopt'
// `_getpgid'
// `_getpgrp'
// `_getpwnam'
// `_getrlimit'
// `_getrusage'
// `_isatty'
// `_killpg'
// `__longjmp'
// `_malloc'
// `_opendir'
// `_opterr'
// `_optind'
// `_optopt'
// `_optreset'
// `_pipe'
// `_readdir'
// `_realloc'
// `_select'
// `_setenv'
// `__setjmp'
// `_setlocale' // STUB
// `_setmode'
// `_setpgid' 
// `_setrlimit' // STUB
// `_sigaction' // SIG
// `_sigemptyset' // SIG
// `_siginterrupt' // SIG
// `_signal' // SIG
// `_sigprocmask' // SIG
// `_snprintf'
// `_sprintf'
// `_strerror'
// `_strtoimax'
// `_sys_siglist' // SIG
// `_tcgetpgrp'
// `_tcsetattr'
// `_tcsetpgrp'
// `_unsetenv'
// `_vfprintf'
// `_wait3'
