
// Takie symbole siê nie rozwi±zuj±... pomó¿my im ;)
// Tym razem nvi... ma niez³e wymagania, nie ma co...

// _access'
// `_atol'
// `_bsearch'
// `_chmod'
// `_chown'
// `_clearerr'
// `_ctime'
// `_execl'
// `_ferror'
// `_fstat'
// `_fsync'
// `_ftruncate'
// `_getgrnam'
// `_getpwuid'
// `_gettimeofday'
// `_idlok'
// `_iscntrl'
// `_isprint'
// `_mkdir'
// `_mkstemp'
// `_mmap'
// `_munmap'
// `_revoke'
// `_setvbuf'
// `_strsep'
// `_strtoul'
// `_system'
// `_time'
// `_toupper'
// `_ttyname'
// `_unlink'
// `_vfork'
// `_waddnstr'
// `_waitpid'
// `_writev'
