LIBRARY= libfs
CFLAGS=${_K_FLAGS}

SRCS=\
    fstable.c\
    devfs/devfs.c\
    mfs/mfs.c\
    fatfs/fat_node.c\
    fatfs/fat_main.c\
    fatfs/fat_dirent.c\
    fifofs/fifofs.c


include ${IMPALA_MK}/lib.mk

