LIBRARY= libarch
C_FLAGS=-D__KERNEL ${C_FLAGS_} 

SRCS=\
	arch/asmstub.s\
	arch/bootstrap.s\
	arch/init.c\
	arch/interrupt.c\
	arch/isr.s\
	arch/thread.c\
    dev/i8254.c\
	dev/i8259a.c\
	dev/video.c\








include ${IMPALA_MK}/lib.mk
