LIBRARY= libarch
CFLAGS=-D__KERNEL ${_K_FLAGS} 

SRCS=\
	arch/asmstub.s\
	arch/bootstrap.s\
	arch/init.c\
	arch/interrupt.c\
	arch/isr.s\
	arch/memory.c\
	arch/thread.c\
	dev/bus_isa.c\
	dev/bus_pci.c\
	dev/i8254.c\
	dev/i8259a.c\
	dev/pckbd.c\
	dev/video.c\








include ${IMPALA_MK}/lib.mk
