LIBRARY=libz
SRCS = adler32.c compress.c crc32.c gzio.c uncompr.c deflate.c trees.c \
       zutil.c inflate.c infback.c inftrees.c inffast.c
PREFIX=${AOUT_PREFIX}
CFLAGS=${_U_FLAGS} -DSTDC

include ${IMPALA_MK}/lib.mk
