LIBRARY= libc
PREFIX=${AOUT_PREFIX}
CFLAGS=${_U_FLAGS}
INCDIR=-Iinclude -Iprivate
SRCS=\
	fcntl/open.c\
	stdlib/atexit.c\
	string/memchr.c\
        string/memcmp.c\
        string/memcpy.c\
        string/memmove.c\
        string/memset.c\
        string/strcat.c\
        string/strchr.c\
        string/strcmp.c\
        string/strcoll.c\
        string/strcpy.c\
        string/strcspn.c\
        string/strlen.c\
        string/strncat.c\
        string/strncmp.c\
        string/strncpy.c\
        string/strpbrk.c\
        string/strrchr.c\
        string/strspn.c\
        string/strtok.c\
        string/strxfrm.c\
	unistd/close.c\
	unistd/lseek.c\
	unistd/getpid.c\
	unistd/getppid.c\
	unistd/getuid.c\
	unistd/setuid.c\
	unistd/read.c\
	unistd/write.c\

include ${IMPALA_MK}/lib.mk
