LIBRARY= libc
PREFIX=${AOUT_PREFIX}
CFLAGS=${_U_FLAGS}
INCDIR=-Iinclude -Iprivate
SRCS=\
	stdlib/atexit.c\
        string/memchr.c\
        string/memcmp.c\
        string/memcpy.c\
        string/memmove.c\
        string/memset.c\
        string/strcat.c\
        string/strchr.c\
        string/strcmp.c\
        string/strcpy.c\
        string/strlen.c\
        string/strncat.c\
        string/strncmp.c\
        string/strncpy.c\
        string/strrchr.c\
	unistd/write.c\

include ${IMPALA_MK}/lib.mk
